---
title: "District_Cost_of_Cultivation"
format: html
editor: visual
---

# Wheat

```{r}
library(rio)
P2017_18_withDistNames=import("P2017_18_withDistNames.csv")

P2017_18_withDistNames_Wheat=subset(P2017_18_withDistNames,P2017_18_withDistNames$Crop=="Wheat")


#P2017_18_withDistNames_Wheat_Insecticides=subset(P2017_18_withDistNames_Wheat,select=c("Insecticides (Rs.)","District name"))
#P2017_18_withDistNames_Wheat_Insecticides_pos=subset(P2017_18_withDistNames_Wheat_Insecticides,P2017_18_withDistNames_Wheat_Insecticides$`Insecticides (Rs.)`>0)

library(dplyr)
P2017_18_withDistNames_Wheat=rename(P2017_18_withDistNames_Wheat,District=`District name`)
P2017_18_withDistNames_Wheat=rename(P2017_18_withDistNames_Wheat,TehsilName=`Tehsil name`)

P2017_18_withDistNames_Wheat=na_if(P2017_18_withDistNames_Wheat, 0)

library(data.table)
P2017_18_withDistNames_Wheat=data.table(P2017_18_withDistNames_Wheat)

#Fertilizer
P2017_18_withDistNames_Wheat$FertiliserNRsperKg=P2017_18_withDistNames_Wheat$`Fertiliser (N) (Rs.)`/P2017_18_withDistNames_Wheat$`Fertiliser (N) (Kg.)`
P2017_18_withDistNames_Wheat$FertiliserPRsperKg=P2017_18_withDistNames_Wheat$`Fertiliser (P) (Rs.)`/P2017_18_withDistNames_Wheat$`Fertiliser (P) (Kg.)`
P2017_18_withDistNames_Wheat$FertiliserKRsperKg=P2017_18_withDistNames_Wheat$`Fertiliser (K) (Rs.)`/P2017_18_withDistNames_Wheat$`Fertiliser (K) (Kg.)`

#Irrigation
P2017_18_withDistNames_Wheat$OwnedIrrigationMachineRsperhr=P2017_18_withDistNames_Wheat$`Owned Irrigation Machine (Rs.)`/P2017_18_withDistNames_Wheat$`Owned Irrigation Machine (Hrs.)`
P2017_18_withDistNames_Wheat$HiredIrrigationMachineRsperhr=P2017_18_withDistNames_Wheat$`Hired Irrigation Machine (Rs.)`/P2017_18_withDistNames_Wheat$`Hired Irrigation Machine (Hrs.)`

#Labor
P2017_18_withDistNames_Wheat$FamilyLabourRsperHr=P2017_18_withDistNames_Wheat$`Family Labour (Rs.)`/P2017_18_withDistNames_Wheat$`Family Labour (Hrs.)`
P2017_18_withDistNames_Wheat$FamilyLabourRsperHa=P2017_18_withDistNames_Wheat$`Family Labour (Rs.)`/P2017_18_withDistNames_Wheat$`Crop Area (Ha.)`
P2017_18_withDistNames_Wheat$FamilyLabourHrsperHa=P2017_18_withDistNames_Wheat$`Family Labour (Hrs.)`/P2017_18_withDistNames_Wheat$`Crop Area (Ha.)`

P2017_18_withDistNames_Wheat$CasualLabourRsperHr=P2017_18_withDistNames_Wheat$`Casual Labour (Rs.)`/P2017_18_withDistNames_Wheat$`Casual Labour (Hrs.)`
P2017_18_withDistNames_Wheat$CasualLabourRsperHa=P2017_18_withDistNames_Wheat$`Casual Labour (Rs.)`/P2017_18_withDistNames_Wheat$`Crop Area (Ha.)`
P2017_18_withDistNames_Wheat$CasualLabourHrsperHa=P2017_18_withDistNames_Wheat$`Casual Labour (Hrs.)`/P2017_18_withDistNames_Wheat$`Crop Area (Ha.)`







P2017_18_withDistNames_Wheat_Inputs=subset(P2017_18_withDistNames_Wheat,
                                           select=c("FertiliserNRsperKg","FertiliserPRsperKg","FertiliserKRsperKg",
                                                    "OwnedIrrigationMachineRsperhr","HiredIrrigationMachineRsperhr",
                                                    "FamilyLabourRsperHr","CasualLabourRsperHr","FamilyLabourRsperHa",
                                                    "FamilyLabourHrsperHa","CasualLabourRsperHa","CasualLabourHrsperHa","District"
                                                    ))
P2017_18_withDistNames_Wheat_Inputs_dist=P2017_18_withDistNames_Wheat_Inputs[,lapply(.SD,median,na.rm=TRUE),by=District]


P2017_18_withDistNames_Wheat_Inputs2=subset(P2017_18_withDistNames_Wheat,
                                           select=c("FertiliserNRsperKg","FertiliserPRsperKg","FertiliserKRsperKg",
                                                    "OwnedIrrigationMachineRsperhr","HiredIrrigationMachineRsperhr",
                                                    "FamilyLabourRsperHr","CasualLabourRsperHr","FamilyLabourRsperHa",
                                                    "FamilyLabourHrsperHa","CasualLabourRsperHa","CasualLabourHrsperHa","TehsilName"))
                                           
P2017_18_withDistNames_Wheat_Inputs_tehsil=P2017_18_withDistNames_Wheat_Inputs2[,lapply(.SD,median,na.rm=TRUE),by=TehsilName]

P2017_18_withDistNames_Wheat_Inputs_dist$District[P2017_18_withDistNames_Wheat_Inputs_dist$District=="East Champaran"]="EastChamparan"
P2017_18_withDistNames_Wheat_Inputs_dist$District[P2017_18_withDistNames_Wheat_Inputs_dist$District=="West Champaran"]="WestChamparan"
P2017_18_withDistNames_Wheat_Inputs_dist$District[P2017_18_withDistNames_Wheat_Inputs_dist$District=="Sitamadhi"]="Sitamarhi"


write.csv(P2017_18_withDistNames_Wheat_Inputs_dist,"data/P2017_18_withDistNames_Wheat_Inputs_dist.csv")


```

```{r}
library(rio)
P2017_18_withDistNames=import("P2017_18_withDistNames.csv")

P2017_18_withDistNames_Wheat=subset(P2017_18_withDistNames,P2017_18_withDistNames$Crop=="Wheat")


#P2017_18_withDistNames_Wheat_Insecticides=subset(P2017_18_withDistNames_Wheat,select=c("Insecticides (Rs.)","District name"))
#P2017_18_withDistNames_Wheat_Insecticides_pos=subset(P2017_18_withDistNames_Wheat_Insecticides,P2017_18_withDistNames_Wheat_Insecticides$`Insecticides (Rs.)`>0)

library(dplyr)
P2017_18_withDistNames_Wheat=rename(P2017_18_withDistNames_Wheat,District=`District name`)
P2017_18_withDistNames_Wheat=rename(P2017_18_withDistNames_Wheat,TehsilName=`Tehsil name`)

P2017_18_withDistNames_Wheat=na_if(P2017_18_withDistNames_Wheat, 0)

library(data.table)
P2017_18_withDistNames_Wheat=data.table(P2017_18_withDistNames_Wheat)

#Fertilizer
P2017_18_withDistNames_Wheat$FertiliserNRsperKg=P2017_18_withDistNames_Wheat$`Fertiliser (N) (Rs.)`/P2017_18_withDistNames_Wheat$`Fertiliser (N) (Kg.)`
P2017_18_withDistNames_Wheat$FertiliserPRsperKg=P2017_18_withDistNames_Wheat$`Fertiliser (P) (Rs.)`/P2017_18_withDistNames_Wheat$`Fertiliser (P) (Kg.)`
P2017_18_withDistNames_Wheat$FertiliserKRsperKg=P2017_18_withDistNames_Wheat$`Fertiliser (K) (Rs.)`/P2017_18_withDistNames_Wheat$`Fertiliser (K) (Kg.)`

#Irrigation
P2017_18_withDistNames_Wheat$OwnedIrrigationMachineRsperhr=P2017_18_withDistNames_Wheat$`Owned Irrigation Machine (Rs.)`/P2017_18_withDistNames_Wheat$`Owned Irrigation Machine (Hrs.)`
P2017_18_withDistNames_Wheat$HiredIrrigationMachineRsperhr=P2017_18_withDistNames_Wheat$`Hired Irrigation Machine (Rs.)`/P2017_18_withDistNames_Wheat$`Hired Irrigation Machine (Hrs.)`

#Labor
P2017_18_withDistNames_Wheat$FamilyLabourRsperHr=P2017_18_withDistNames_Wheat$`Family Labour (Rs.)`/P2017_18_withDistNames_Wheat$`Family Labour (Hrs.)`
P2017_18_withDistNames_Wheat$FamilyLabourRsperHa=P2017_18_withDistNames_Wheat$`Family Labour (Rs.)`/P2017_18_withDistNames_Wheat$`Crop Area (Ha.)`
P2017_18_withDistNames_Wheat$FamilyLabourHrsperHa=P2017_18_withDistNames_Wheat$`Family Labour (Hrs.)`/P2017_18_withDistNames_Wheat$`Crop Area (Ha.)`

P2017_18_withDistNames_Wheat$CasualLabourRsperHr=P2017_18_withDistNames_Wheat$`Casual Labour (Rs.)`/P2017_18_withDistNames_Wheat$`Casual Labour (Hrs.)`
P2017_18_withDistNames_Wheat$CasualLabourRsperHa=P2017_18_withDistNames_Wheat$`Casual Labour (Rs.)`/P2017_18_withDistNames_Wheat$`Crop Area (Ha.)`
P2017_18_withDistNames_Wheat$CasualLabourHrsperHa=P2017_18_withDistNames_Wheat$`Casual Labour (Hrs.)`/P2017_18_withDistNames_Wheat$`Crop Area (Ha.)`







P2017_18_withDistNames_Wheat_Inputs=subset(P2017_18_withDistNames_Wheat,
                                           select=c("FertiliserNRsperKg","FertiliserPRsperKg","FertiliserKRsperKg",
                                                    "OwnedIrrigationMachineRsperhr","HiredIrrigationMachineRsperhr",
                                                    "FamilyLabourRsperHr","CasualLabourRsperHr","FamilyLabourRsperHa",
                                                    "FamilyLabourHrsperHa","CasualLabourRsperHa","CasualLabourHrsperHa","District"
                                                    ))
P2017_18_withDistNames_Wheat_Inputs_dist=P2017_18_withDistNames_Wheat_Inputs[,lapply(.SD,median,na.rm=TRUE),by=District]


P2017_18_withDistNames_Wheat_Inputs2=subset(P2017_18_withDistNames_Wheat,
                                           select=c("FertiliserNRsperKg","FertiliserPRsperKg","FertiliserKRsperKg",
                                                    "OwnedIrrigationMachineRsperhr","HiredIrrigationMachineRsperhr",
                                                    "FamilyLabourRsperHr","CasualLabourRsperHr","FamilyLabourRsperHa",
                                                    "FamilyLabourHrsperHa","CasualLabourRsperHa","CasualLabourHrsperHa","TehsilName"))
                                           
P2017_18_withDistNames_Wheat_Inputs_tehsil=P2017_18_withDistNames_Wheat_Inputs2[,lapply(.SD,median,na.rm=TRUE),by=TehsilName]

P2017_18_withDistNames_Wheat_Inputs_dist$District[P2017_18_withDistNames_Wheat_Inputs_dist$District=="East Champaran"]="EastChamparan"
P2017_18_withDistNames_Wheat_Inputs_dist$District[P2017_18_withDistNames_Wheat_Inputs_dist$District=="West Champaran"]="WestChamparan"
P2017_18_withDistNames_Wheat_Inputs_dist$District[P2017_18_withDistNames_Wheat_Inputs_dist$District=="Sitamadhi"]="Sitamarhi"


write.csv(P2017_18_withDistNames_Wheat_Inputs_dist,"data/P2017_18_withDistNames_Wheat_Inputs_dist.csv")
```

# Rice
