---
title: "Rice-Wheat System Spatial Multivariate Modeling Approach"
format: 
    html:
      code-fold: true
      code-tools: true
fig-dpi: 300
fig-align: center

self-contained: true
author: Maxwell Mkondiwa
editor: visual
toc: true
toc-location: left
number-sections: true
execute: 
  message: false
  warning: false
  echo: true
---

# Introduction

```{r}



#rm(list = ls())
if (!require("pacman")) install.packages("pacman")
pacman::p_load(sp, mgcv, bamlss,BayesX,R2BayesX,sf,spdep,rio,distreg.vis)

setwd("C:/Users/MMKONDIWA/OneDrive - CIMMYT/Documents/GitHub/Rice_Wheat_System_SDS_Tool")
# Multivariate geoadditive model
# remotes::install_git("https://git.uibk.ac.at/c4031039/mvnchol")
#
library(sp)
library (mgcv)
library(mvnchol)
library(BayesX)
library(R2BayesX)
library(sf)
library(spdep)
library(rio)

Irrig_Rev_rice_wheat <- import("data/Irrig_Rev_rice_wheat_Updated.csv")

Irrig_Rev_rice_wheat$Longitude=Irrig_Rev_rice_wheat$o_largest_plot_gps_longitude
Irrig_Rev_rice_wheat$Latitude=Irrig_Rev_rice_wheat$o_largest_plot_gps_latitude

Irrig_Rev_rice_wheat <- subset(Irrig_Rev_rice_wheat, !(is.na(Irrig_Rev_rice_wheat$Longitude)))
Irrig_Rev_rice_wheat <- subset(Irrig_Rev_rice_wheat, !(is.na(Irrig_Rev_rice_wheat$Latitude)))

Irrig_Rev_rice_wheat <- subset(Irrig_Rev_rice_wheat, !(is.na(Irrig_Rev_rice_wheat$o_largest_plot_gps_longitude)))
Irrig_Rev_rice_wheat <- subset(Irrig_Rev_rice_wheat, !(is.na(Irrig_Rev_rice_wheat$o_largest_plot_gps_latitude)))

library(janitor)
library(tidyr)


Irrig_Rev_rice_wheat <- clean_names(Irrig_Rev_rice_wheat)

Irrig_Rev_rice_wheat$c_q306_crop_larest_area_ha <- Irrig_Rev_rice_wheat$c_q306_crop_larest_area_acre*0.405

Irrig_Rev_rice_wheat$harvest_day_rice <- Irrig_Rev_rice_wheat$l_crop_duration_days_rice + Irrig_Rev_rice_wheat$sowdate_fmt_rice_day


shpname <- file.path(getwd(), "shp", "India_aoi_sf_sp")

India_aoi_sp_bnd <- BayesX::shp2bnd(shpname = shpname, regionnames = "District", check.is.in = F)

# Multivariate geoadditive model
# remotes::install_git("https://git.uibk.ac.at/c4031039/mvnchol")
# install_github("https://github.com/meteosimon/mvnchol")
library(mvnchol)

# Remove NAs in the monsoon variables
Irrig_Rev_rice_wheat <- subset(Irrig_Rev_rice_wheat, !(is.na(Irrig_Rev_rice_wheat$onset_2017)))
Irrig_Rev_rice_wheat <- subset(Irrig_Rev_rice_wheat, !(is.na(Irrig_Rev_rice_wheat$monsoon_onset_dev)))
Irrig_Rev_rice_wheat <- subset(Irrig_Rev_rice_wheat, !(is.na(Irrig_Rev_rice_wheat$median_onset_82_15)))
Irrig_Rev_rice_wheat <- subset(Irrig_Rev_rice_wheat, !(is.na(Irrig_Rev_rice_wheat$sd_onset_82_15)))


K <- neighbormatrix(India_aoi_sp_bnd)
head(K)

## Also need to transform to factor for
## setting up the MRF smooth.
Irrig_Rev_rice_wheat$District <- as.factor(Irrig_Rev_rice_wheat$a_q103_district)

## Now note that not all regions are observed,
## therefore we need to remove those regions
## from the penalty matrix
rn <- rownames(K)
lv <- levels(Irrig_Rev_rice_wheat$District)
i <- rn %in% lv
K <- K[i, i]

set.seed(321)
library(bamlss)

nd <- data.frame("District" = unique(Irrig_Rev_rice_wheat$District))

```

# Non-structural: Bivariate gaussian

## Yield analysis
```{r}
# Bivariate gaussian 
## Formulas
biv_gauss_yield<- list(
  b_grain_yield_ton_per_ha_rice ~ 1, 
  l_ton_per_hectare ~ 1, 
  sigma1 ~ 1, 
  sigma2 ~ 1,
  rho ~ 1
)

## Model fitting
biv_gauss_yield_model <- bamlss(biv_gauss_yield, family = bamlss:::bivnorm_bamlss, data = Irrig_Rev_rice_wheat,
  burnin = 2000, thin = 10, n.iter = 12000, sampler = TRUE, nu = 1)


summary(biv_gauss_yield_model)

## Prediction
biv_gauss_yield_model_pred <- predict(biv_gauss_yield_model, type = "parameter")

biv_gauss_yield_model_pred= as.data.frame(biv_gauss_yield_model_pred)


# Yield analysis

# Bivariate gaussian 
## Formulas
f_biv_gauss_yld_non_struct <- list(
b_grain_yield_ton_per_ha_rice ~ 1 + rice_duration_class_long + s(sowdate_fmt_rice_day) + s(g_q5305_irrig_times_rice) + s(nperha_rice) + s(p2o5perha_rice) + 
   s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+
  +may_tmin_17+jun_tmin_17+jul_tmin_17+aug_tmin_17+sep_tmin_17+oct_tmin_17+
    may_tmax_17+jun_tmax_17+jul_tmax_17+aug_tmax_17+sep_tmax_17+oct_tmax_17+may_prec_17+jun_prec_17+jul_prec_17+aug_prec_17+sep_prec_17+oct_prec_17+
  s(District, bs = "mrf", xt = list("penalty" = K)) + s(District, bs = "re"),
  



l_ton_per_hectare ~ 1 + variety_type_nmwv + s(sowdate_fmt_wheat_day) + g_q5305_irrig_times + s(nperha) + s(p2o5perha) +weedmanaged+
    s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+jan_tmin_18+feb_tmin_18+mar_tmin_18+apr_tmin_18+jan_tmax_18+feb_tmax_18+
    mar_tmax_18+apr_tmax_18+jan_prec_18+feb_prec_18+mar_prec_18+apr_prec_18 + s(District, bs = "mrf", xt = list("penalty" = K)) + s(District, bs = "re"),




  sigma1 ~ 1 + rice_duration_class_long + s(sowdate_fmt_rice_day) + s(g_q5305_irrig_times_rice) + s(nperha_rice) + s(p2o5perha_rice) + 
   s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+
  +may_tmin_17+jun_tmin_17+jul_tmin_17+aug_tmin_17+sep_tmin_17+oct_tmin_17+
    may_tmax_17+jun_tmax_17+jul_tmax_17+aug_tmax_17+sep_tmax_17+oct_tmax_17+may_prec_17+jun_prec_17+jul_prec_17+aug_prec_17+sep_prec_17+oct_prec_17+ s(District, bs = "mrf", xt = list("penalty" = K)) + s(District, bs = "re"), 

  sigma2 ~ 1 + variety_type_nmwv + s(sowdate_fmt_wheat_day) + g_q5305_irrig_times + s(nperha) + s(p2o5perha) +weedmanaged+
    s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+jan_tmin_18+feb_tmin_18+mar_tmin_18+apr_tmin_18+jan_tmax_18+feb_tmax_18+
    mar_tmax_18+apr_tmax_18+jan_prec_18+feb_prec_18+mar_prec_18+apr_prec_18 + s(District, bs = "mrf", xt = list("penalty" = K)) + s(District, bs = "re"),

  rho ~ 1+s(sowdate_fmt_rice_day)+s(sowdate_fmt_wheat_day)+s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+s(District, bs = "mrf", xt = list("penalty" = K)) + s(District, bs = "re")
)

## Model fitting
biv_gauss_yld_non_struct <- bamlss(f_biv_gauss_yld_non_struct, family = bamlss:::bivnorm_bamlss, data = Irrig_Rev_rice_wheat,
  burnin = 2000, thin = 10, n.iter = 12000, sampler = TRUE, nu = 1)


summary(biv_gauss_yld_non_struct)


par(mfrow = c(2, 3), mar = c(4, 4, 1, 1))
plot(biv_gauss_yld_non_struct, pages = 1, spar = FALSE, rug = TRUE)



## Prediction
  
## Prediction
biv_gauss_yld_non_struct_pred <- predict(biv_gauss_yld_non_struct, type = "parameter")

biv_gauss_yld_non_struct_pred= as.data.frame(biv_gauss_yld_non_struct_pred)

# Predictions of impact of sowing dates on yield,yield risk and correlation
Biv_Rice_sow_date_pred <- data.frame("sowdate_fmt_rice_day" = seq(min(biv_gauss_yld_non_struct$model.frame$sowdate_fmt_rice_day), max(biv_gauss_yld_non_struct$model.frame$sowdate_fmt_rice_day), length = 95))


     
# 
Biv_Rice_sow_date_pred$mu1_CI <- predict(biv_gauss_yld_non_struct, newdata = Biv_Rice_sow_date_pred, model = "mu1", term = "sowdate_fmt_rice_day",
   FUN = c95, intercept = FALSE)

 ylim <- range(c(Biv_Rice_sow_date_pred$mu1_CI))
 
png(file="figures/Biv_sowing_rice_plot_unstruct.png", width=350, height=250)
 
bamlss::plot2d(mu1_CI ~ sowdate_fmt_rice_day, data = Biv_Rice_sow_date_pred, ylim = ylim,xlab="Rice transplanting date", lwd = c(1,3,1),col.lines = "#2E9FDF")

dev.off()


# Impact on Rho

Biv_Rice_sow_date_pred$rho_CI <- predict(biv_gauss_yld_non_struct, newdata = Biv_Rice_sow_date_pred, model = "rho", term = "sowdate_fmt_rice_day",
   FUN = c95, intercept = FALSE)

 ylim <- range(c(Biv_Rice_sow_date_pred$rho_CI))
 
png(file="figures/Biv_Rice_sow_date_pred_rho_plot_unstruct.png", width=350, height=250)
 
bamlss::plot2d(rho_CI ~ sowdate_fmt_rice_day, data = Biv_Rice_sow_date_pred, ylim = ylim,xlab="Rice transplanting date", lwd = c(1,3,1),col.lines = "#2E9FDF", main="Effect on correlation")

dev.off()





# Rice and wheat sowing dates impacts
Biv_Rice_wheat_sow_date_pred <- expand.grid(sowdate_fmt_rice_day = seq(min(biv_gauss_yld_non_struct$model.frame$sowdate_fmt_rice_day), max(biv_gauss_yld_non_struct$model.frame$sowdate_fmt_rice_day), length = 100),sowdate_fmt_wheat_day = seq(min(biv_gauss_yld_non_struct$model.frame$sowdate_fmt_wheat_day), max(biv_gauss_yld_non_struct$model.frame$sowdate_fmt_wheat_day), length = 100))


Biv_Rice_wheat_sow_date_pred$mu1_CI <- predict(biv_gauss_yld_non_struct, newdata = Biv_Rice_wheat_sow_date_pred, model = "mu1", term = c("sowdate_fmt_rice_day","sowdate_fmt_wheat_day"),
   FUN = c95, intercept = FALSE)

Biv_Rice_wheat_sow_date_pred$sigma1_CI <- predict(biv_gauss_yld_non_struct, newdata = Biv_Rice_wheat_sow_date_pred, model = "sigma1", term = c("sowdate_fmt_rice_day","sowdate_fmt_wheat_day"),
   FUN = c95, intercept = FALSE)

Biv_Rice_wheat_sow_date_pred$mu2_CI <- predict(biv_gauss_yld_non_struct, newdata = Biv_Rice_wheat_sow_date_pred, model = "mu2", term = c("sowdate_fmt_rice_day","sowdate_fmt_wheat_day"),
   FUN = c95, intercept = FALSE)

Biv_Rice_wheat_sow_date_pred$sigma2_CI <- predict(biv_gauss_yld_non_struct, newdata = Biv_Rice_wheat_sow_date_pred, model = "sigma2", term = c("sowdate_fmt_rice_day","sowdate_fmt_wheat_day"),
   FUN = c95, intercept = FALSE)

Biv_Rice_wheat_sow_date_pred$rho_CI <- predict(biv_gauss_yld_non_struct, newdata = Biv_Rice_wheat_sow_date_pred, model = "rho", term = c("sowdate_fmt_rice_day","sowdate_fmt_wheat_day"),
   FUN = c95, intercept = FALSE)



par(mfrow = c(2, 3), mar = c(4, 4, 1, 1))
bamlss::plot2d(mu1_CI  ~ sowdate_fmt_rice_day, data = Biv_Rice_wheat_sow_date_pred,xlab="Rice transplanting date", lwd = c(1,3,1),col.lines = "#2E9FDF", main="Effect on rice mean")

bamlss::plot2d(sigma1_CI  ~ sowdate_fmt_rice_day, data = Biv_Rice_wheat_sow_date_pred,xlab="Rice transplanting date", lwd = c(1,3,1),col.lines = "#2E9FDF", main="Effect on log rice variance")

bamlss::plot2d(rho_CI  ~ sowdate_fmt_rice_day, data = Biv_Rice_wheat_sow_date_pred,xlab="Rice transplanting date", lwd = c(1,3,1),col.lines = "#2E9FDF", main="Effect on rice-yield correlation")


bamlss::plot2d(mu2_CI  ~ sowdate_fmt_wheat_day, data = Biv_Rice_wheat_sow_date_pred,xlab="Wheat sowing date", lwd = c(1,3,1),col.lines = "#2E9FDF", main="Effect on wheat mean")

bamlss::plot2d(sigma2_CI  ~ sowdate_fmt_wheat_day, data = Biv_Rice_wheat_sow_date_pred,xlab="Wheat sowing date", lwd = c(1,3,1),col.lines = "#2E9FDF", main="Effect on log wheat variance")

bamlss::plot2d(rho_CI  ~ sowdate_fmt_wheat_day, data = Biv_Rice_wheat_sow_date_pred,xlab="Wheat sowing date", lwd = c(1,3,1),col.lines = "#2E9FDF", main="Effect on rice-yield correlation")

library(ggplot2)

        
ggplot(Biv_Rice_wheat_sow_date_pred) + 
  geom_tile(aes(sowdate_fmt_rice_day,sowdate_fmt_wheat_day, fill=rho_CI$Mean ))+
  geom_contour(aes(x=sowdate_fmt_rice_day,y=sowdate_fmt_wheat_day, z=rho_CI$Mean,colour = after_stat(level)))+
  scale_fill_gradientn(colors = hcl.colors(20, "RdYlGn")) +
  coord_fixed()+
  labs(x="Rice sowing date",y="Wheat sowing date")+
  theme_bw()

library(metR)


sowdate_heatmap_corr_yield=ggplot(Biv_Rice_wheat_sow_date_pred,    aes(sowdate_fmt_rice_day,sowdate_fmt_wheat_day, z = rho_CI$Mean )) +
  geom_contour_fill(aes(fill = after_stat(level)))+
  coord_fixed()+
  labs(x="Rice sowing date",y="Wheat sowing date",fill="Rice-wheat yield \n correlation")+
  theme_bw()
sowdate_heatmap_corr_yield

ggsave("figures/sowdate_heatmap_corr_yield.png")




# Mapping Correlations
biv_gauss_yld_non_struct_fitted_values <- biv_gauss_yld_non_struct$fitted

biv_gauss_yld_non_struct_fitted_values <- as.data.frame(biv_gauss_yld_non_struct_fitted_values)

# Merge the fitted results to the data and export

Irrig_Rev_rice_wheat_Mult_Res <- cbind(biv_gauss_yld_non_struct$model.frame, biv_gauss_yld_non_struct_fitted_values)

#write.csv(Irrig_Rev_rice_wheat_Mult_Res, "tables/Irrig_Rev_rice_wheat_Mult_Res.csv")

summary(lm(sowdate_fmt_rice_day ~ mu1, Irrig_Rev_rice_wheat_Mult_Res))

summary(lm(b_grain_yield_ton_per_ha_rice ~ l_ton_per_hectare, Irrig_Rev_rice_wheat_Mult_Res))


#Irrig_Rev_rice_wheat_Mult_Res_sp <- Irrig_Rev_rice_wheat_Mult_Res
#coordinates(Irrig_Rev_rice_wheat_Mult_Res_sp) <- c("o_largest_plot_gps_longitude", "o_largest_plot_gps_latitude")

# Map the correlations
library(modelsummary)
Irrig_Rev_rice_wheat_Mult_Res_dist <- datasummary(Heading("District") * District ~ Heading("N obs") * N + Heading("%") * Percent() + rho * (Mean + SD), data = Irrig_Rev_rice_wheat_Mult_Res, output = "data.frame")

library(dplyr)
Irrig_Rev_rice_wheat_Mult_Res_dist <- rename(Irrig_Rev_rice_wheat_Mult_Res_dist, "Mean_Rice_Wheat_Rho" = "Mean")
Irrig_Rev_rice_wheat_Mult_Res_dist <- rename(Irrig_Rev_rice_wheat_Mult_Res_dist, "SD_Rice_Wheat_Rho" = "SD")

Irrig_Rev_rice_wheat_Mult_Res_dist <- subset(Irrig_Rev_rice_wheat_Mult_Res_dist, Irrig_Rev_rice_wheat_Mult_Res_dist$District != "Purnia")


# Bihar and EUP map
# India district Map

library(geodata)

India <- gadm(country = "IND", level = 2, path = "shp")

plot(India)

India_aoi <- subset(India, India$NAME_1 == "Bihar" | India$NAME_2 %in% c("Ballia", "Chandauli", "Deoria", "Ghazipur", "Kushinagar", "Maharajganj", "Mau", "Siddharth Nagar", "Gorakhpur"))

plot(India_aoi)

plot(India_aoi, add = TRUE)

library(sf)

India_aoi_sf <- st_as_sf(India_aoi)
library(mapview)

mapview(India_aoi_sf)

# Dissolve the district polygons to form new polygon of Bihar and EUP
library(sf)
India_aoi_sf_dis <- st_union(India_aoi_sf)
mapview(India_aoi_sf_dis)

###
library(modelsummary)

India_aoi_sf$District <- India_aoi_sf$NAME_2

India_aoi_sf$District[India_aoi_sf$District == "Purba Champaran"] <- "EastChamparan"
India_aoi_sf$District[India_aoi_sf$District == "Pashchim Champaran"] <- "WestChamparan"
India_aoi_sf$District[India_aoi_sf$District == "Bhojpur"] <- "Arah"
India_aoi_sf$District[India_aoi_sf$District == "Ballia"] <- "Balia"
India_aoi_sf$District[India_aoi_sf$District == "Ghazipur"] <- "Gazipur"
India_aoi_sf$District[India_aoi_sf$District == "Siddharth Nagar"] <- "Siddharthnagar"


rice_wheat_yield_rho_dist_sf <- merge(India_aoi_sf, Irrig_Rev_rice_wheat_Mult_Res_dist, by = "District")

rice_wheat_yield_rho_dist_sf$Mean_Rice_Wheat_Rho <- as.numeric(rice_wheat_yield_rho_dist_sf$Mean_Rice_Wheat_Rho)
library(mapview)
mapview(rice_wheat_yield_rho_dist_sf, zcol = "Mean_Rice_Wheat_Rho", layer.name = "Rice wheat equation correlation")
library(sf)
rice_wheat_yield_rho_dist_sf_sp <- as_Spatial(rice_wheat_yield_rho_dist_sf)
library(tmap)
tmap_mode("plot")
rice_wheat_yield_rho_dist_sf_sp_map <- tm_shape(rice_wheat_yield_rho_dist_sf_sp) +
  tm_polygons(col = "Mean_Rice_Wheat_Rho", title = "Rice wheat equation correlation",style="quantile",palette = "YlGn") +
  tm_layout(legend.outside = TRUE)

rice_wheat_yield_rho_dist_sf_sp_map

tmap_save(rice_wheat_yield_rho_dist_sf_sp_map, "figures/Bivariate_rice_wheat_yield_rho_dist_sf_sp_map.png", width=4.16, height=3.16)


#
## Predict for the structured spatial effects.
p_str_biv_gauss_yld_non_struct <- predict(biv_gauss_yld_non_struct, newdata = nd, term = "s(District,id='mrf1')", FUN = c95, intercept = FALSE)

p_str_biv_gauss_yld_non_struct_dt <- as.data.frame(p_str_biv_gauss_yld_non_struct)

#write.csv(p_str_biv_gauss_yld_non_struct_mu1_dt, "tables/p_str_biv_gauss_yld_non_struct_mu1_dt.csv")

## And the unstructured spatial effect.
p_unstr_biv_gauss_yld_non_struct<- predict(biv_gauss_yld_non_struct, newdata = nd, term = "s(District,id='re2')",FUN = c95, intercept = FALSE)

# Rice yield spatial equation
plotmap(India_aoi_sp_bnd, x = p_str_biv_gauss_yld_non_struct$mu1$Mean, id = nd$District, main = expression(mu(rice_yield)), title = "Structured spatial effect")

plotmap(India_aoi_sp_bnd, x = p_unstr_biv_gauss_yld_non_struct$mu1$Mean, id = nd$District, main = expression(mu(rice_yield)), title = "Unstructured spatial effect")

plotmap(India_aoi_sp_bnd, x = p_str_biv_gauss_yld_non_struct$sigma1$Mean, id = nd$District, main = expression(sigma(rice_yield)), title = "Structured spatial effect")

plotmap(India_aoi_sp_bnd, x = p_unstr_biv_gauss_yld_non_struct$sigma1$Mean, id = nd$District, main = expression(sigma(rice_yield)), title = "Unstructured spatial effect")


plotmap(India_aoi_sp_bnd, x = p_str_biv_gauss_yld_non_struct$mu2$Mean, id = nd$District, main = expression(mu(wheat_yield)), title = "Structured spatial effect")

plotmap(India_aoi_sp_bnd, x = p_unstr_biv_gauss_yld_non_struct$mu2$Mean, id = nd$District, main = expression(mu(wheat_yield)), title = "Unstructured spatial effect")

plotmap(India_aoi_sp_bnd, x = p_str_biv_gauss_yld_non_struct$sigma2$Mean, id = nd$District, main = expression(sigma(wheat_yield)), title = "Structured spatial effect")

plotmap(India_aoi_sp_bnd, x = p_unstr_biv_gauss_yld_non_struct$sigma2$Mean, id = nd$District, main = expression(sigma(weat_yield)), title = "Unstructured spatial effect")

png(file="figures/p_unstr_biv_gauss_yld_non_struct_sigma2_Mean,.png",
width=350, height=250)

plotmap(India_aoi_sp_bnd, x = p_unstr_biv_gauss_yld_non_struct$sigma2$Mean, id = nd$District, main = expression(sigma(weat_yield)), title = "Unstructured spatial effect")

dev.off()

# Focusing on the cross-equation correlations

## MRF smooth effect.
plotmap(India_aoi_sp_bnd,
        x = p_str_biv_gauss_yld_non_struct$rho$Mean, id = nd$District,
        main = expression(rho(rice, wheat)), title = "Structured spatial effect"
)

## Random effects.
plotmap(India_aoi_sp_bnd,
        x = p_unstr_biv_gauss_yld_non_struct$rho$Mean, id = nd$District, main = expression(rho(rice, wheat)), title = "Unstructured spatial effect"
)

p_str_biv_gauss_yld_non_struct_dt=as.data.frame(p_str_biv_gauss_yld_non_struct)

colnames(p_str_biv_gauss_yld_non_struct_dt)=paste(colnames(p_str_biv_gauss_yld_non_struct_dt),"_","str")

p_unstr_str_biv_gauss_yld_non_struct_dt=cbind(nd,p_unstr_biv_gauss_yld_non_struct,p_str_biv_gauss_yld_non_struct_dt)

# Significant tests
# rice
p_unstr_str_biv_gauss_yld_non_struct_dt$mu1_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`mu1.2.5%`>0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`mu1.97.5%`>0]="Positive significant"
p_unstr_str_biv_gauss_yld_non_struct_dt$mu1_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`mu1.2.5%`<0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`mu1.97.5%`<0]="Negative significant"
p_unstr_str_biv_gauss_yld_non_struct_dt$mu1_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`mu1.2.5%`<0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`mu1.97.5%`>0]="Not significant"

p_unstr_str_biv_gauss_yld_non_struct_dt$mu1_str_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`mu1.2.5. _ str`>0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`mu1.97.5. _ str`>0]="Positive significant"
p_unstr_str_biv_gauss_yld_non_struct_dt$mu1_str_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`mu1.2.5. _ str`<0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`mu1.97.5. _ str`<0]="Negative significant"
p_unstr_str_biv_gauss_yld_non_struct_dt$mu1_str_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`mu1.2.5. _ str`<0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`mu1.97.5. _ str`>0]="Not significant"

p_unstr_str_biv_gauss_yld_non_struct_dt$sigma1_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma1.2.5%`>0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma1.97.5%`>0]="Positive significant"
p_unstr_str_biv_gauss_yld_non_struct_dt$sigma1_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma1.2.5%`<0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma1.97.5%`<0]="Negative significant"
p_unstr_str_biv_gauss_yld_non_struct_dt$sigma1_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma1.2.5%`<0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma1.97.5%`>0]="Not significant"

p_unstr_str_biv_gauss_yld_non_struct_dt$sigma1_str_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma1.2.5. _ str`>0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma1.97.5. _ str`>0]="Positive significant"
p_unstr_str_biv_gauss_yld_non_struct_dt$sigma1_str_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma1.2.5. _ str`<0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma1.97.5. _ str`<0]="Negative significant"
p_unstr_str_biv_gauss_yld_non_struct_dt$sigma1_str_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma1.2.5. _ str`<0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma1.97.5. _ str`>0]="Not significant"

# wheat
p_unstr_str_biv_gauss_yld_non_struct_dt$mu2_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`mu2.2.5%`>0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`mu2.97.5%`>0]="Positive significant"
p_unstr_str_biv_gauss_yld_non_struct_dt$mu2_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`mu2.2.5%`<0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`mu2.97.5%`<0]="Negative significant"
p_unstr_str_biv_gauss_yld_non_struct_dt$mu2_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`mu2.2.5%`<0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`mu2.97.5%`>0]="Not significant"

p_unstr_str_biv_gauss_yld_non_struct_dt$mu2_str_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`mu2.2.5. _ str`>0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`mu2.97.5. _ str`>0]="Positive significant"
p_unstr_str_biv_gauss_yld_non_struct_dt$mu2_str_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`mu2.2.5. _ str`<0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`mu2.97.5. _ str`<0]="Negative significant"
p_unstr_str_biv_gauss_yld_non_struct_dt$mu2_str_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`mu2.2.5. _ str`<0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`mu2.97.5. _ str`>0]="Not significant"




p_unstr_str_biv_gauss_yld_non_struct_dt$sigma2_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma2.2.5%`>0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma2.97.5%`>0]="Positive significant"
p_unstr_str_biv_gauss_yld_non_struct_dt$sigma2_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma2.2.5%`<0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma2.97.5%`<0]="Negative significant"
p_unstr_str_biv_gauss_yld_non_struct_dt$sigma2_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma2.2.5%`<0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma2.97.5%`>0]="Not significant"

p_unstr_str_biv_gauss_yld_non_struct_dt$sigma2_str_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma2.2.5. _ str`>0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma2.97.5. _ str`>0]="Positive significant"
p_unstr_str_biv_gauss_yld_non_struct_dt$sigma2_str_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma2.2.5. _ str`<0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma2.97.5. _ str`<0]="Negative significant"
p_unstr_str_biv_gauss_yld_non_struct_dt$sigma2_str_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma2.2.5. _ str`<0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`sigma2.97.5. _ str`>0]="Not significant"

# significance for correlations
p_unstr_str_biv_gauss_yld_non_struct_dt$rho_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`rho.2.5%`>0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`rho.97.5%`>0]="Positive significant"
p_unstr_str_biv_gauss_yld_non_struct_dt$rho_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`rho.2.5%`<0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`rho.97.5%`<0]="Negative significant"
p_unstr_str_biv_gauss_yld_non_struct_dt$rho_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`rho.2.5%`<0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`rho.97.5%`>0]="Not significant"

p_unstr_str_biv_gauss_yld_non_struct_dt$rho_str_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`rho.2.5. _ str`>0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`rho.97.5. _ str`>0]="Positive significant"
p_unstr_str_biv_gauss_yld_non_struct_dt$rho_str_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`rho.2.5. _ str`<0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`rho.97.5. _ str`<0]="Negative significant"
p_unstr_str_biv_gauss_yld_non_struct_dt$rho_str_sign[p_unstr_str_biv_gauss_yld_non_struct_dt$`rho.2.5. _ str`<0 & p_unstr_str_biv_gauss_yld_non_struct_dt$`rho.97.5. _ str`>0]="Not significant"



# Using GGPLOT2
p_unstr_str_biv_gauss_yld_non_struct_dt_sf <- merge(India_aoi_sf, p_unstr_str_biv_gauss_yld_non_struct_dt, by = "District")

library(sf)
p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp <- as_Spatial(p_unstr_str_biv_gauss_yld_non_struct_dt_sf)

#
library(tmap)
tmap_mode("plot")

#mu1
p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu1_str <- tm_shape(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp) +
  tm_polygons(col = "mu1.Mean._.str", title = "Structured spatial effects \n on mean rice yield", ,palette = "YlGn") +
  tm_layout(legend.outside = TRUE)
#style="quantile"
p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu1_str

tmap_save(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu1_str, "figures/p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu1_str.png", width=4.16, height=3.16)

p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu1_str_sign <- tm_shape(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp) +
  tm_polygons(col = "mu1_str_sign", title = "Structured spatial effects \n on mean rice yield", ,palette = "YlGn") +
  tm_layout(legend.outside = TRUE)
p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu1_str_sign

tmap_save(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu1_str_sign, "figures/p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu1_str_sign.png", width=4.16, height=3.16)


#mu1 unstr
p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu1_unstr <- tm_shape(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp) +
  tm_polygons(col = "mu1.Mean", title = "Unstructured spatial effects \n on mean rice yield",palette = "YlGn") +
  tm_layout(legend.outside = TRUE)

p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu1_unstr

tmap_save(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu1_unstr, "figures/p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu1_unstr.png", width=4.16, height=3.16)


p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu1_unstr_sign <- tm_shape(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp) +
  tm_polygons(col = "mu1_sign", title = "Unstructured spatial effects \n on mean rice yield",palette = "YlGn") +
  tm_layout(legend.outside = TRUE)

p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu1_unstr_sign

tmap_save(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu1_unstr_sign, "figures/p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu1_unstr_sign.png", width=4.16, height=3.16)

# sigma1

p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma1_str <- tm_shape(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp) +
  tm_polygons(col = "sigma1.Mean._.str", title = "Structured spatial effects \n on rice yield risk", ,palette = "YlGn") +
  tm_layout(legend.outside = TRUE)
#style="quantile"
p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma1_str

tmap_save(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma1_str, "figures/p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma1_str.png", width=4.16, height=3.16)

p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma1_str_sign <- tm_shape(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp) +
  tm_polygons(col = "sigma1_str_sign", title = "Structured spatial effects \n on rice yield risk", ,palette = "YlGn") +
  tm_layout(legend.outside = TRUE)
p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma1_str_sign

tmap_save(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma1_str_sign, "figures/p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma1_str_sign.png", width=4.16, height=3.16)


#sigma1 unstr
p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma1_unstr <- tm_shape(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp) +
  tm_polygons(col = "sigma1.Mean", title = "Unstructured spatial effects \n on rice yield risk",palette = "YlGn") +
  tm_layout(legend.outside = TRUE)

p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma1_unstr

tmap_save(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma1_unstr, "figures/p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma1_unstr.png", width=4.16, height=3.16)


p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma1_unstr_sign <- tm_shape(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp) +
  tm_polygons(col = "sigma1_sign", title = "Unstructured spatial effects \n on rice yield risk",palette = "YlGn") +
  tm_layout(legend.outside = TRUE)

p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma1_unstr_sign

tmap_save(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma1_unstr_sign, "figures/p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma1_unstr_sign.png", width=4.16, height=3.16)



# Wheat
#mu2
p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu2_str <- tm_shape(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp) +
  tm_polygons(col = "mu2.Mean._.str", title = "Structured spatial effects \n on mean wheat yield", ,palette = "YlGn") +
  tm_layout(legend.outside = TRUE)

p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu2_str

tmap_save(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu2_str, "figures/p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu2_str.png", width=4.16, height=3.16)

p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu2_str_sign <- tm_shape(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp) +
  tm_polygons(col = "mu2_str_sign", title = "Structured spatial effects \n on mean wheat yield", ,palette = "YlGn") +
  tm_layout(legend.outside = TRUE)
p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu2_str_sign

tmap_save(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu2_str_sign, "figures/p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu2_str_sign.png", width=4.16, height=3.16)


#mu2 unstr
p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu2_unstr <- tm_shape(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp) +
  tm_polygons(col = "mu2.Mean", title = "Unstructured spatial effects \n on mean wheat yield",palette = "YlGn") +
  tm_layout(legend.outside = TRUE)

p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu2_unstr

tmap_save(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu2_unstr, "figures/p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu2_unstr.png", width=4.16, height=3.16)


p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu2_unstr_sign <- tm_shape(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp) +
  tm_polygons(col = "mu2_sign", title = "Unstructured spatial effects \n on mean wheat yield",palette = "YlGn") +
  tm_layout(legend.outside = TRUE)

p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu2_unstr_sign

tmap_save(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu2_unstr_sign, "figures/p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_mu2_unstr_sign.png", width=4.16, height=3.16)

# sigma 2
#sigma2
p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma2_str <- tm_shape(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp) +
  tm_polygons(col = "sigma2.Mean._.str", title = "Structured spatial effects \n on wheat yield risk", ,palette = "YlGn") +
  tm_layout(legend.outside = TRUE)

p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma2_str

tmap_save(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma2_str, "figures/p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma2_str.png", width=4.16, height=3.16)

p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma2_str_sign <- tm_shape(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp) +
  tm_polygons(col = "sigma2_str_sign", title = "Structured spatial effects \n on wheat yield risk", ,palette = "YlGn") +
  tm_layout(legend.outside = TRUE)
p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma2_str_sign

tmap_save(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma2_str_sign, "figures/p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma2_str_sign.png", width=4.16, height=3.16)


#sigma2 unstr
p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma2_unstr <- tm_shape(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp) +
  tm_polygons(col = "sigma2.Mean", title = "Unstructured spatial effects \n on wheat yield risk",palette = "YlGn") +
  tm_layout(legend.outside = TRUE)

p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma2_unstr

tmap_save(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma2_unstr, "figures/p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma2_unstr.png", width=4.16, height=3.16)


p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma2_unstr_sign <- tm_shape(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp) +
  tm_polygons(col = "sigma2_sign", title = "Unstructured spatial effects \n on wheat yield risk",palette = "YlGn") +
  tm_layout(legend.outside = TRUE)

p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma2_unstr_sign

tmap_save(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma2_unstr_sign, "figures/p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sigma2_unstr_sign.png", width=4.16, height=3.16)



# Correlation

library(mapview)
mapview(p_unstr_str_biv_gauss_yld_non_struct_dt_sf, zcol = "rho.Mean", layer.name = "Unstructured spatial effects on rho")


library(tmap)
tmap_mode("plot")
p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_rhomean <- tm_shape(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp) +
  tm_polygons(col = "rho.Mean", title = "Unstructured spatial effects on \n rice-wheat yield correlation",palette = "YlGn") +
  tm_layout(legend.outside = TRUE)

p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_rhomean

tmap_save(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_rhomean, "figures/p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_rhomean.png", width=4.16, height=3.16)


p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sign <- tm_shape(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp) +
  tm_polygons(col = "rho_sign", title = "Unstructured spatial effects on \n rice-wheat yield correlation",palette = "YlGn") +
  tm_layout(legend.outside = TRUE)

p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sign

tmap_save(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sign, "figures/p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_sign.png", width=4.16, height=3.16)


library(tmap)
tmap_mode("plot")
p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_rhomean_str <- tm_shape(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp) +
  tm_polygons(col = "rho.Mean._.str", title = "Structured spatial effects on \n rice-wheat yield correlation",palette = "YlGn") +
  tm_layout(legend.outside = TRUE)

p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_rhomean_str

tmap_save(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_rhomean_str, "figures/p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_rhomean_str.png", width=4.16, height=3.16)

p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_rhosign_str <- tm_shape(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp) +
  tm_polygons(col = "rho_str_sign", title = "Structured spatial effects on \n rice-wheat yield correlation",palette = "YlGn") +
  tm_layout(legend.outside = TRUE)

p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_rhosign_str

tmap_save(p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_rhosign_str, "figures/p_unstr_str_biv_gauss_yld_non_struct_dt_sf_sp_map_rhosign_str.png", width=4.16, height=3.16)

```


## Revenue analysis
```{r}
# Bivariate gaussian 
## Formulas
biv_gauss_rev <- list(
  revenue_rice ~ 1, 
  revenue_wheat ~ 1, 
  sigma1 ~ 1, 
  sigma2 ~ 1,
  rho ~ 1
)

## Model fitting
biv_gauss_rev_model <- bamlss(biv_gauss_rev, family = bamlss:::bivnorm_bamlss, data = Irrig_Rev_rice_wheat,
  burnin = 2000, thin = 10, n.iter = 12000, sampler = TRUE, nu = 1)


summary(biv_gauss_rev_model)
## Prediction
biv_gauss_rev_model_pred <- predict(biv_gauss_rev_model, type = "parameter")

biv_gauss_rev_model_pred= as.data.frame(biv_gauss_rev_model_pred)


# Revenue analysis
Irrig_Rev_rice_wheat$revenue_rice_000=Irrig_Rev_rice_wheat$revenue_rice/1000
Irrig_Rev_rice_wheat$revenue_wheat_000=Irrig_Rev_rice_wheat$revenue_wheat/1000

# Bivariate gaussian 
## Formulas
f_biv_gauss_rev_non_struct <- list(
revenue_rice_000 ~ 1 + rice_duration_class_long + s(sowdate_fmt_rice_day) + s(g_q5305_irrig_times_rice) + s(nperha_rice) + s(p2o5perha_rice) + 
   s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+
  +may_tmin_17+jun_tmin_17+jul_tmin_17+aug_tmin_17+sep_tmin_17+oct_tmin_17+
    may_tmax_17+jun_tmax_17+jul_tmax_17+aug_tmax_17+sep_tmax_17+oct_tmax_17+may_prec_17+jun_prec_17+jul_prec_17+aug_prec_17+sep_prec_17+oct_prec_17+
  s(District, bs = "mrf", xt = list("penalty" = K)) + s(District, bs = "re"),
  



revenue_wheat_000 ~ 1 + variety_type_nmwv + s(sowdate_fmt_wheat_day) + g_q5305_irrig_times + s(nperha) + s(p2o5perha) +weedmanaged+
    s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+jan_tmin_18+feb_tmin_18+mar_tmin_18+apr_tmin_18+jan_tmax_18+feb_tmax_18+
    mar_tmax_18+apr_tmax_18+jan_prec_18+feb_prec_18+mar_prec_18+apr_prec_18 + s(District, bs = "mrf", xt = list("penalty" = K)) + s(District, bs = "re"),




  sigma1 ~ 1 + rice_duration_class_long + s(sowdate_fmt_rice_day) + s(g_q5305_irrig_times_rice) + s(nperha_rice) + s(p2o5perha_rice) + 
   s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+
  +may_tmin_17+jun_tmin_17+jul_tmin_17+aug_tmin_17+sep_tmin_17+oct_tmin_17+
    may_tmax_17+jun_tmax_17+jul_tmax_17+aug_tmax_17+sep_tmax_17+oct_tmax_17+may_prec_17+jun_prec_17+jul_prec_17+aug_prec_17+sep_prec_17+oct_prec_17+ s(District, bs = "mrf", xt = list("penalty" = K)) + s(District, bs = "re"), 

  sigma2 ~ 1 + variety_type_nmwv + s(sowdate_fmt_wheat_day) + g_q5305_irrig_times + s(nperha) + s(p2o5perha) +weedmanaged+
    s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+jan_tmin_18+feb_tmin_18+mar_tmin_18+apr_tmin_18+jan_tmax_18+feb_tmax_18+
    mar_tmax_18+apr_tmax_18+jan_prec_18+feb_prec_18+mar_prec_18+apr_prec_18 + s(District, bs = "mrf", xt = list("penalty" = K)) + s(District, bs = "re"),

  rho ~ 1+s(sowdate_fmt_rice_day)+s(sowdate_fmt_wheat_day)+s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+s(District, bs = "mrf", xt = list("penalty" = K)) + s(District, bs = "re")
)

## Model fitting
biv_gauss_rev_non_struct <- bamlss(f_biv_gauss_rev_non_struct, family = bamlss:::bivnorm_bamlss, data = Irrig_Rev_rice_wheat,
  burnin = 2000, thin = 10, n.iter = 12000, sampler = TRUE, nu = 1)


summary(biv_gauss_rev_non_struct)


par(mfrow = c(2, 3), mar = c(4, 4, 1, 1))
plot(biv_gauss_rev_non_struct, pages = 1, spar = FALSE, rug = TRUE)


## Prediction
biv_gauss_rev_non_struct_pred <- predict(biv_gauss_rev_non_struct, type = "parameter")

biv_gauss_rev_non_struct_pred= as.data.frame(biv_gauss_rev_non_struct_pred)

# Rice and wheat sowing dates impacts
Biv_Rice_wheat_sow_date_pred_rev <- expand.grid(sowdate_fmt_rice_day = seq(min(biv_gauss_rev_non_struct$model.frame$sowdate_fmt_rice_day), max(biv_gauss_rev_non_struct$model.frame$sowdate_fmt_rice_day), length = 10),sowdate_fmt_wheat_day = seq(min(biv_gauss_rev_non_struct$model.frame$sowdate_fmt_wheat_day), max(biv_gauss_rev_non_struct$model.frame$sowdate_fmt_wheat_day), length = 10))


Biv_Rice_wheat_sow_date_pred_rev$mu1_CI <- predict(biv_gauss_rev_non_struct, newdata = Biv_Rice_wheat_sow_date_pred_rev, model = "mu1", term = c("sowdate_fmt_rice_day","sowdate_fmt_wheat_day"),
   FUN = c95, intercept = FALSE)

Biv_Rice_wheat_sow_date_pred_rev$sigma1_CI <- predict(biv_gauss_rev_non_struct, newdata = Biv_Rice_wheat_sow_date_pred_rev, model = "sigma1", term = c("sowdate_fmt_rice_day","sowdate_fmt_wheat_day"),
   FUN = c95, intercept = FALSE)

Biv_Rice_wheat_sow_date_pred_rev$mu2_CI <- predict(biv_gauss_rev_non_struct, newdata = Biv_Rice_wheat_sow_date_pred_rev, model = "mu2", term = c("sowdate_fmt_rice_day","sowdate_fmt_wheat_day"),
   FUN = c95, intercept = FALSE)

Biv_Rice_wheat_sow_date_pred_rev$sigma2_CI <- predict(biv_gauss_rev_non_struct, newdata = Biv_Rice_wheat_sow_date_pred_rev, model = "sigma2", term = c("sowdate_fmt_rice_day","sowdate_fmt_wheat_day"),
   FUN = c95, intercept = FALSE)

Biv_Rice_wheat_sow_date_pred_rev$rho_CI <- predict(biv_gauss_rev_non_struct, newdata = Biv_Rice_wheat_sow_date_pred_rev, model = "rho", term = c("sowdate_fmt_rice_day","sowdate_fmt_wheat_day"),
   FUN = c95, intercept = FALSE)



par(mfrow = c(2, 3), mar = c(4, 4, 1, 1))
bamlss::plot2d(mu1_CI  ~ sowdate_fmt_rice_day, data = Biv_Rice_wheat_sow_date_pred_rev,xlab="Rice transplanting date", lwd = c(1,3,1),col.lines = "#2E9FDF", main="Effect on rice revenue (000) mean")

bamlss::plot2d(sigma1_CI  ~ sowdate_fmt_rice_day, data = Biv_Rice_wheat_sow_date_pred_rev,xlab="Rice transplanting date", lwd = c(1,3,1),col.lines = "#2E9FDF", main="Effect on log rice revenue (000) variance")

bamlss::plot2d(rho_CI  ~ sowdate_fmt_rice_day, data = Biv_Rice_wheat_sow_date_pred_rev,xlab="Rice transplanting date",col.lines = "#2E9FDF", main="Effect on rice-yield correlation")


bamlss::plot2d(mu2_CI  ~ sowdate_fmt_wheat_day, data = Biv_Rice_wheat_sow_date_pred_rev,xlab="Wheat sowing date", lwd = c(1,3,1),col.lines = "#2E9FDF", main="Effect on wheat revenue (000) mean")

bamlss::plot2d(sigma2_CI  ~ sowdate_fmt_wheat_day, data = Biv_Rice_wheat_sow_date_pred_rev,xlab="Wheat sowing date", lwd = c(1,3,1),col.lines = "#2E9FDF", main="Effect on log wheat revenue (000) variance")

bamlss::plot2d(rho_CI  ~ sowdate_fmt_wheat_day, data = Biv_Rice_wheat_sow_date_pred_rev,xlab="Wheat sowing date", lwd = c(1,3,1),col.lines = "#2E9FDF", main="Effect on rice-yield correlation")

library(ggplot2)

        
ggplot(Biv_Rice_wheat_sow_date_pred_rev) + 
  geom_tile(aes(sowdate_fmt_rice_day,sowdate_fmt_wheat_day, fill=rho_CI$Mean ))+
  geom_contour(aes(x=sowdate_fmt_rice_day,y=sowdate_fmt_wheat_day, z=rho_CI$Mean,colour = after_stat(level)))+
  scale_fill_gradientn(colors = hcl.colors(20, "RdYlGn")) +
  coord_fixed()+
  labs(x="Rice sowing date",y="Wheat sowing date")+
  theme_bw()

library(metR)


sowdate_heatmap_corr_rev=ggplot(Biv_Rice_wheat_sow_date_pred_rev,    aes(sowdate_fmt_rice_day,sowdate_fmt_wheat_day, z = rho_CI$Mean )) +
  geom_contour_fill(aes(fill = after_stat(level)))+
  coord_fixed()+
  labs(x="Rice sowing date",y="Wheat sowing date",fill="Rice-wheat revenue \n correlation")+
  theme_bw()
sowdate_heatmap_corr_rev

ggsave("figures/sowdate_heatmap_corr_rev.png",width=5,height=3.5)

# Impact on total revenues 

Biv_Rice_wheat_sow_date_pred_rev$total_revenue_effect=Biv_Rice_wheat_sow_date_pred_rev$mu1_CI$Mean+Biv_Rice_wheat_sow_date_pred_rev$mu2_CI$Mean

sowdate_heatmap_mu1_mu2_rev=ggplot(Biv_Rice_wheat_sow_date_pred_rev,    aes(sowdate_fmt_rice_day,sowdate_fmt_wheat_day, z = total_revenue_effect )) +
  geom_contour_fill(aes(fill = after_stat(level)),binwidth=5)+
  coord_fixed()+
  labs(x="Rice sowing date",y="Wheat sowing date",fill="Effect on total \n rice-wheat revenue (000)")+
  theme_bw()
sowdate_heatmap_mu1_mu2_rev

ggsave("figures/sowdate_heatmap_mu1_mu2_rev.png", width=5,height=3.5)

# Impact on standard deviation
Biv_Rice_wheat_sow_date_pred_rev$total_revenue_std_dev_effect=exp(Biv_Rice_wheat_sow_date_pred_rev$sigma1_CI$Mean)+exp(Biv_Rice_wheat_sow_date_pred_rev$sigma2_CI$Mean)

sowdate_heatmap_sigma1_sigma2_rev=ggplot(Biv_Rice_wheat_sow_date_pred_rev,    aes(sowdate_fmt_rice_day,sowdate_fmt_wheat_day, z = total_revenue_std_dev_effect )) +
  geom_contour_fill(aes(fill = after_stat(level)))+
  coord_fixed()+
  labs(x="Rice sowing date",y="Wheat sowing date",fill="Effect on total \n R-W revenue (000) Std.Dev")+
  theme_bw()
sowdate_heatmap_sigma1_sigma2_rev

ggsave("figures/sowdate_heatmap_sigma1_sigma2_rev.png", width=5,height=3.5)

library(cowplot)

plot_grid(sowdate_heatmap_mu1_mu2_rev,sowdate_heatmap_sigma1_sigma2_rev,sowdate_heatmap_corr_rev, ncol = 2, nrow = 2) 

ggsave("figures/sowdate_heatmap_cowplot.png", width=5,height=3.5)

# ggplot(Biv_Rice_wheat_sow_date_pred_rev,    aes(total_revenue_std_dev_effect,total_revenue_effect, z = list(sowdate_fmt_rice_day,sowdate_fmt_wheat_day))) +
#   geom_contour_fill(aes(fill = after_stat(level)))+
#   coord_fixed()+
#   labs(x="Standard deviation",y="Mean",fill="Sowing date")+
#   theme_bw()



# Mean-Standard Deviation Relationship
library(ggplot2)
ggplot(Biv_Rice_wheat_sow_date_pred_rev,aes(x = total_revenue_std_dev_effect, 
                   y = total_revenue_effect, 
                   color =sowdate_fmt_rice_day)) +
    geom_point() +
   geom_text(aes(label = sowdate_fmt_wheat_day),
            size = 3) 


```

# Risk, return and certainty equivalent analysis
```{r}
Biv_Rice_wheat_sow_date_pred_rev$total_revenue_variance_effect=(Biv_Rice_wheat_sow_date_pred_rev$total_revenue_std_dev_effect)^2

# Cost of risk

Biv_Rice_wheat_sow_date_pred_rev$rice_wheat_risk_cost_1=0.5*1*((Biv_Rice_wheat_sow_date_pred_rev$total_revenue_variance_effect)/(Biv_Rice_wheat_sow_date_pred_rev$total_revenue_effect))

Biv_Rice_wheat_sow_date_pred_rev$rice_wheat_risk_cost_2=0.5*2*((Biv_Rice_wheat_sow_date_pred_rev$total_revenue_variance_effect)/(Biv_Rice_wheat_sow_date_pred_rev$total_revenue_effect))

Biv_Rice_wheat_sow_date_pred_rev$rice_wheat_risk_cost_3=0.5*3*((Biv_Rice_wheat_sow_date_pred_rev$total_revenue_variance_effect)/(Biv_Rice_wheat_sow_date_pred_rev$total_revenue_effect))

Biv_Rice_wheat_sow_date_pred_rev$rice_wheat_risk_cost_4=0.5*4*((Biv_Rice_wheat_sow_date_pred_rev$total_revenue_variance_effect)/(Biv_Rice_wheat_sow_date_pred_rev$total_revenue_effect))

Biv_Rice_wheat_sow_date_pred_rev$rice_wheat_risk_cost_5=0.5*5*((Biv_Rice_wheat_sow_date_pred_rev$total_revenue_variance_effect)/(Biv_Rice_wheat_sow_date_pred_rev$total_revenue_effect))

# Certainty equivalent

Biv_Rice_wheat_sow_date_pred_rev$CE_1=Biv_Rice_wheat_sow_date_pred_rev$total_revenue_effect-Biv_Rice_wheat_sow_date_pred_rev$rice_wheat_risk_cost_1

Biv_Rice_wheat_sow_date_pred_rev$CE_2=Biv_Rice_wheat_sow_date_pred_rev$total_revenue_effect-Biv_Rice_wheat_sow_date_pred_rev$rice_wheat_risk_cost_2

Biv_Rice_wheat_sow_date_pred_rev$CE_3=Biv_Rice_wheat_sow_date_pred_rev$total_revenue_effect-Biv_Rice_wheat_sow_date_pred_rev$rice_wheat_risk_cost_3

Biv_Rice_wheat_sow_date_pred_rev$CE_4=Biv_Rice_wheat_sow_date_pred_rev$total_revenue_effect-Biv_Rice_wheat_sow_date_pred_rev$rice_wheat_risk_cost_4

Biv_Rice_wheat_sow_date_pred_rev$CE_5=Biv_Rice_wheat_sow_date_pred_rev$total_revenue_effect-Biv_Rice_wheat_sow_date_pred_rev$rice_wheat_risk_cost_5

# Heatmap of CE from from low risk aversion to high risk aversion

CE_1_plot=ggplot(subset(Biv_Rice_wheat_sow_date_pred_rev,Biv_Rice_wheat_sow_date_pred_rev$CE_1>0),    aes(sowdate_fmt_rice_day,sowdate_fmt_wheat_day, z = CE_1)) +
  geom_contour_fill(aes(fill = after_stat(level)),binwidth=2)+
  coord_fixed()+
  labs(x="Rice sowing date",y="Wheat sowing date",fill="Certainty \n equivalence (000)",title="Low risk aversion (1)")+
  theme_bw()
CE_1_plot

ggsave("figures/CE_1_plot.png", width=4,height=3)

CE_2_plot=ggplot(subset(Biv_Rice_wheat_sow_date_pred_rev,Biv_Rice_wheat_sow_date_pred_rev$CE_2>0),    aes(sowdate_fmt_rice_day,sowdate_fmt_wheat_day, z = CE_2)) +
  geom_contour_fill(aes(fill = after_stat(level)),binwidth=2)+
  coord_fixed()+
  labs(x="Rice sowing date",y="Wheat sowing date",fill="Certainty \n equivalence (000)",title="Low risk aversion 2")+
  theme_bw()
CE_2_plot

ggsave("figures/CE_2_plot.png", width=4,height=3)

CE_3_plot=ggplot(subset(Biv_Rice_wheat_sow_date_pred_rev,Biv_Rice_wheat_sow_date_pred_rev$CE_3>0),    aes(sowdate_fmt_rice_day,sowdate_fmt_wheat_day, z = CE_3)) +
  geom_contour_fill(aes(fill = after_stat(level)),binwidth=2)+
  coord_fixed()+
  labs(x="Rice sowing date",y="Wheat sowing date",fill="Certainty \n equivalence (000)",title="Moderate risk aversion 3")+
  theme_bw()
CE_3_plot

ggsave("figures/CE_3_plot.png", width=4,height=3)

CE_4_plot=ggplot(subset(Biv_Rice_wheat_sow_date_pred_rev,Biv_Rice_wheat_sow_date_pred_rev$CE_4>0),    aes(sowdate_fmt_rice_day,sowdate_fmt_wheat_day, z = CE_4)) +
  geom_contour_fill(aes(fill = after_stat(level)),binwidth=2)+
  coord_fixed()+
  labs(x="Rice sowing date",y="Wheat sowing date",fill="Certainty \n equivalence (000)",title="Moderate risk aversion 4")+
  theme_bw()
CE_4_plot

ggsave("figures/CE_4_plot.png", width=4,height=3)


CE_5_plot=ggplot(subset(Biv_Rice_wheat_sow_date_pred_rev,Biv_Rice_wheat_sow_date_pred_rev$CE_5>0),    aes(sowdate_fmt_rice_day,sowdate_fmt_wheat_day, z = CE_5)) +
  geom_contour_fill(aes(fill = after_stat(level)),binwidth=2)+
  coord_fixed()+
  labs(x="Rice sowing date",y="Wheat sowing date",fill="Certainty \n equivalence (000)",title="High risk aversion 5")+
  theme_bw()
CE_5_plot

ggsave("figures/CE_5_plot.png", width=4,height=3)

library(cowplot)

plot_grid(CE_1_plot,CE_3_plot,CE_4_plot,CE_5_plot, ncol = 2, nrow = 2) 

ggsave("figures/CE_plots.png")


# Crop specific optimization
## rice


## wheat




#





```

#Structural: Bivariate gaussian

##First stage
```{r}
f_sow_rice_1st_stage <- list(
  sowdate_fmt_rice_day ~ 1 + rice_duration_class_long +gw_2017 +onset_2017+ monsoon_onset_dev + median_onset_82_15 +sd_onset_82_15+
    s(District, bs = "mrf", xt = list("penalty" = K)) +
    s(District, bs = "re")
)

#d_q401_soil_texture+d_q402_drain_class+m_q702_hh_mem_ag+m_q708_market_distance+irrig_source+a_q112_f_edu_new+ 
#population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+               
#soc_5_15cm+
#c_q306_crop_larest_area_acre+may_prec_17+jun_prec_17+jul_prec_17+may_tmin_17+jun_tmin_17+                 jul_tmin_17+may_tmax_17+jun_tmax_17+jul_tmax_17+

f_sow_rice_1st_stage_MRF <- bamlss(f_sow_rice_1st_stage, data = Irrig_Rev_rice_wheat, family = "gaussian")

summary(f_sow_rice_1st_stage_MRF)

fitted_f_sow_rice_1st_stage_MRF <- f_sow_rice_1st_stage_MRF$fitted

Irrig_Rev_rice_wheat$Res_rice_sow <- Irrig_Rev_rice_wheat$sowdate_fmt_rice_day - fitted_f_sow_rice_1st_stage_MRF$mu



par(mfrow = c(2, 3), mar = c(4, 4, 1, 1))
plot(f_sow_rice_1st_stage_MRF, pages = 1, spar = FALSE, rug = TRUE)


# Wheat first stage
f_sow_wheat_1st_stage <- list(
  sowdate_fmt_wheat_day ~ 1 + variety_type_nmwv + s(harvest_day_rice)+ 
    s(District, bs = "mrf", xt = list("penalty" = K)) +
    s(District, bs = "re")
)
#
#+gw_2018 +
#  c_q306_crop_larest_area_acre+d_q401_soil_texture+d_q402_drain_class+m_q702_hh_mem_ag+m_q708_market_distance+irrig_source+a_q112_f_edu_new+ 
#population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+               
#soc_5_15cm+oct_prec_17+oct_tmin_17+ oct_tmax_17+

f_sow_wheat_1st_stage_MRF <- bamlss(f_sow_wheat_1st_stage, data = Irrig_Rev_rice_wheat, family = "gaussian")

summary(f_sow_wheat_1st_stage_MRF)

fitted_f_sow_wheat_1st_stage_MRF <- f_sow_wheat_1st_stage_MRF$fitted

Irrig_Rev_rice_wheat$Res_wheat_sow <- Irrig_Rev_rice_wheat$sowdate_fmt_wheat_day - fitted_f_sow_wheat_1st_stage_MRF$mu


par(mfrow = c(2, 3), mar = c(4, 4, 1, 1))
plot(f_sow_wheat_1st_stage_MRF, pages = 1, spar = FALSE, rug = TRUE)



```

## Second stage: Yield
```{r}
f_biv_gauss_yld_struct <- list(
b_grain_yield_ton_per_ha_rice ~ 1 + rice_duration_class_long + s(Res_rice_sow) + s(g_q5305_irrig_times_rice) + s(nperha_rice) + s(p2o5perha_rice) +
   s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+
  +may_tmin_17+jun_tmin_17+jul_tmin_17+aug_tmin_17+sep_tmin_17+oct_tmin_17+
    may_tmax_17+jun_tmax_17+jul_tmax_17+aug_tmax_17+sep_tmax_17+oct_tmax_17+may_prec_17+jun_prec_17+jul_prec_17+aug_prec_17+sep_prec_17+oct_prec_17+
  
  s(District, bs = "mrf", xt = list("penalty" = K)) + s(District, bs = "re"),



  l_ton_per_hectare ~ 1 + variety_type_nmwv + s(Res_wheat_sow) + g_q5305_irrig_times + nperha + p2o5perha +
  weedmanaged+
    s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+jan_tmin_18+feb_tmin_18+mar_tmin_18+apr_tmin_18+jan_tmax_18+feb_tmax_18+
    mar_tmax_18+apr_tmax_18+jan_prec_18+feb_prec_18+mar_prec_18+apr_prec_18 +
  s(District, bs = "mrf", xt = list("penalty" = K)) + s(District, bs = "re"),


  sigma1 ~ 1+rice_duration_class_long + s(Res_rice_sow) + s(g_q5305_irrig_times_rice) + s(nperha_rice) + s(p2o5perha_rice) +
   s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+
  +may_tmin_17+jun_tmin_17+jul_tmin_17+aug_tmin_17+sep_tmin_17+oct_tmin_17+
    may_tmax_17+jun_tmax_17+jul_tmax_17+aug_tmax_17+sep_tmax_17+oct_tmax_17+may_prec_17+jun_prec_17+jul_prec_17+aug_prec_17+sep_prec_17+oct_prec_17+
  s(District, bs = "mrf", xt = list("penalty" = K)) + s(District, bs = "re"), 


  sigma2 ~ 1+ variety_type_nmwv + s(Res_wheat_sow) + g_q5305_irrig_times + nperha + p2o5perha + 
  weedmanaged+
    s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+jan_tmin_18+feb_tmin_18+mar_tmin_18+apr_tmin_18+jan_tmax_18+feb_tmax_18+
    mar_tmax_18+apr_tmax_18+jan_prec_18+feb_prec_18+mar_prec_18+apr_prec_18 +
  s(District, bs = "mrf", xt = list("penalty" = K)) + s(District, bs = "re"),


  rho ~ 1+s(Res_rice_sow)+s(Res_wheat_sow)+
  s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+
  +s(District, bs = "mrf", xt = list("penalty" = K)) + s(District, bs = "re")
)

## Model fitting
biv_gauss_yld_struct <- bamlss(f_biv_gauss_yld_struct, family = bamlss:::bivnorm_bamlss, data = Irrig_Rev_rice_wheat,
  burnin = 2000, thin = 10, n.iter = 12000, sampler = TRUE, nu = 1)


summary(biv_gauss_yld_struct)


par(mfrow = c(2, 3), mar = c(4, 4, 1, 1))
plot(biv_gauss_yld_struct, pages = 1, spar = FALSE, rug = TRUE)
dev.off()

```

# Second stage: Revenue
```{r}
Irrig_Rev_rice_wheat$revenue_rice_000=Irrig_Rev_rice_wheat$revenue_rice/1000
Irrig_Rev_rice_wheat$revenue_wheat_000=Irrig_Rev_rice_wheat$revenue_wheat/1000

f_biv_gauss_rev_struct <- list(
revenue_rice_000 ~ 1 + rice_duration_class_long + s(Res_rice_sow) + s(g_q5305_irrig_times_rice) + s(nperha_rice) + s(p2o5perha_rice) +
   s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+
  +may_tmin_17+jun_tmin_17+jul_tmin_17+aug_tmin_17+sep_tmin_17+oct_tmin_17+
    may_tmax_17+jun_tmax_17+jul_tmax_17+aug_tmax_17+sep_tmax_17+oct_tmax_17+may_prec_17+jun_prec_17+jul_prec_17+aug_prec_17+sep_prec_17+oct_prec_17+
  s(District, bs = "mrf", xt = list("penalty" = K)) + s(District, bs = "re"),



  revenue_wheat_000 ~ 1 + variety_type_nmwv + s(Res_wheat_sow) + g_q5305_irrig_times + nperha + p2o5perha + 
  weedmanaged+
    s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+jan_tmin_18+feb_tmin_18+mar_tmin_18+apr_tmin_18+jan_tmax_18+feb_tmax_18+
    mar_tmax_18+apr_tmax_18+jan_prec_18+feb_prec_18+mar_prec_18+apr_prec_18 +
  s(District, bs = "mrf", xt = list("penalty" = K)) + s(District, bs = "re"),


  sigma1 ~ 1+rice_duration_class_long + s(Res_rice_sow) + s(g_q5305_irrig_times_rice) + s(nperha_rice) + s(p2o5perha_rice) +
   s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+
  +may_tmin_17+jun_tmin_17+jul_tmin_17+aug_tmin_17+sep_tmin_17+oct_tmin_17+
    may_tmax_17+jun_tmax_17+jul_tmax_17+aug_tmax_17+sep_tmax_17+oct_tmax_17+may_prec_17+jun_prec_17+jul_prec_17+aug_prec_17+sep_prec_17+oct_prec_17+
  s(District, bs = "mrf", xt = list("penalty" = K)) + s(District, bs = "re"), 


  sigma2 ~ 1+ variety_type_nmwv + s(Res_wheat_sow) + g_q5305_irrig_times + nperha + p2o5perha +
  weedmanaged+
    s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+jan_tmin_18+feb_tmin_18+mar_tmin_18+apr_tmin_18+jan_tmax_18+feb_tmax_18+
    mar_tmax_18+apr_tmax_18+jan_prec_18+feb_prec_18+mar_prec_18+apr_prec_18 +
  s(District, bs = "mrf", xt = list("penalty" = K)) + s(District, bs = "re"),


  rho ~ 1+s(Res_rice_sow)+s(Res_wheat_sow)+s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+
s(District, bs = "mrf", xt = list("penalty" = K)) + s(District, bs = "re")
)

## Model fitting
biv_gauss_rev_struct <- bamlss(f_biv_gauss_rev_struct, family = bamlss:::bivnorm_bamlss, data = Irrig_Rev_rice_wheat,
  burnin = 2000, thin = 10, n.iter = 12000, sampler = TRUE, nu = 1)


summary(biv_gauss_rev_struct)

par(mfrow = c(2, 3), mar = c(4, 4, 1, 1))
plot(biv_gauss_rev_struct, pages = 1, spar = FALSE, rug = TRUE)

save.image("~/GitHub/Rice_Wheat_System_SDS_Tool/Working_space_Struct_Rev_30thApril2025.RData")

## Prediction
biv_gauss_rev_struct_pred <- predict(biv_gauss_rev_struct, type = "parameter")

biv_gauss_rev_struct_pred= as.data.frame(biv_gauss_rev_struct_pred)






```

# Poin-georeferenced analysis
```{r}









```



