---
title: "Rice Model"
format: 
    html:
      code-fold: true
      code-tools: true
fig-dpi: 300
fig-align: center

self-contained: true
author: Maxwell Mkondiwa
editor: visual
toc: true
toc-location: left
number-sections: true
execute: 
  message: false
  warning: false
  echo: true
---

# Rice Yield Model

```{r}
# Rice Model
#rm(list = ls())
if (!require("pacman")) install.packages("pacman")
pacman::p_load(sp, mgcv, bamlss,BayesX,R2BayesX,sf,spdep,rio,distreg.vis)

setwd("C:/Users/MMKONDIWA/OneDrive - CIMMYT/Documents/GitHub/Rice_Wheat_System_SDS_Tool")
# Multivariate geoadditive model
# remotes::install_git("https://git.uibk.ac.at/c4031039/mvnchol")
#
library(mvnchol)
library(BayesX)
library(R2BayesX)
library(sf)
library(spdep)
library(rio)

Irrig_Rev_rice_wheat <- import("data/Irrig_Rev_rice_wheat_Updated.csv")

Irrig_Rev_rice_wheat$Longitude=Irrig_Rev_rice_wheat$o_largest_plot_gps_longitude
Irrig_Rev_rice_wheat$Latitude=Irrig_Rev_rice_wheat$o_largest_plot_gps_latitude

Irrig_Rev_rice_wheat <- subset(Irrig_Rev_rice_wheat, !(is.na(Irrig_Rev_rice_wheat$Longitude)))
Irrig_Rev_rice_wheat <- subset(Irrig_Rev_rice_wheat, !(is.na(Irrig_Rev_rice_wheat$Latitude)))

library(janitor)
library(tidyr)

Irrig_Rev_rice_wheat <- clean_names(Irrig_Rev_rice_wheat)

Irrig_Rev_rice_wheat$c_q306_crop_larest_area_ha <- Irrig_Rev_rice_wheat$c_q306_crop_larest_area_acre*0.405

Irrig_Rev_rice_wheat$harvest_day_rice <- Irrig_Rev_rice_wheat$l_crop_duration_days_rice + Irrig_Rev_rice_wheat$sowdate_fmt_rice_day

shpname <- file.path(getwd(), "shp", "India_aoi_sf_sp")

India_aoi_sp_bnd <- BayesX::shp2bnd(shpname = shpname, regionnames = "District", check.is.in = F)

f_rice_yield_MRF <- list(
  b_grain_yield_ton_per_ha_rice ~ 1 + rice_duration_class_long + s(sowdate_fmt_rice_day) + s(g_q5305_irrig_times_rice) + s(nperha_rice) + s(p2o5perha_rice) +
    s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+may_tmin_17+jun_tmin_17+jul_tmin_17+aug_tmin_17+sep_tmin_17+oct_tmin_17+
    may_tmax_17+jun_tmax_17+jul_tmax_17+aug_tmax_17+sep_tmax_17+oct_tmax_17+may_prec_17+jun_prec_17+jul_prec_17+aug_prec_17+sep_prec_17+oct_prec_17+
    s(District, bs = "mrf", xt = list("penalty" = K)) +
    s(District, bs = "re"),
  sigma ~ 1 + rice_duration_class_long + s(sowdate_fmt_rice_day) + s(g_q5305_irrig_times_rice) + s(nperha_rice) + s(p2o5perha_rice) +
    s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+may_tmin_17+jun_tmin_17+jul_tmin_17+aug_tmin_17+sep_tmin_17+oct_tmin_17+
    may_tmax_17+jun_tmax_17+jul_tmax_17+aug_tmax_17+sep_tmax_17+oct_tmax_17+may_prec_17+jun_prec_17+jul_prec_17+aug_prec_17+sep_prec_17+oct_prec_17+
    s(District, bs = "mrf", xt = list("penalty" = K)) +
    s(District, bs = "re")
)

K <- neighbormatrix(India_aoi_sp_bnd)
head(K)

## Also need to transform to factor for
## setting up the MRF smooth.
Irrig_Rev_rice_wheat$District <- as.factor(Irrig_Rev_rice_wheat$a_q103_district)

## Now note that not all regions are observed,
## therefore we need to remove those regions
## from the penalty matrix
rn <- rownames(K)
lv <- levels(Irrig_Rev_rice_wheat$District)
i <- rn %in% lv
K <- K[i, i]

set.seed(321)
library(bamlss)
b_rice_yield_MRF <- bamlss(f_rice_yield_MRF, data = Irrig_Rev_rice_wheat, family = "gaussian")

summary(b_rice_yield_MRF)


par(mfrow = c(2, 3), mar = c(4, 4, 1, 1))
plot(b_rice_yield_MRF, pages = 1, spar = FALSE, rug = TRUE)

```

# Rice Revenue Model

```{r}

f_rice_rev_MRF <- list(
  revenue_rice ~ 1 + rice_duration_class_long + s(sowdate_fmt_rice_day) + s(g_q5305_irrig_times_rice) + s(nperha_rice) + s(p2o5perha_rice) +
    s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+may_tmin_17+jun_tmin_17+jul_tmin_17+aug_tmin_17+sep_tmin_17+oct_tmin_17+
    may_tmax_17+jun_tmax_17+jul_tmax_17+aug_tmax_17+sep_tmax_17+oct_tmax_17+may_prec_17+jun_prec_17+jul_prec_17+aug_prec_17+sep_prec_17+oct_prec_17+
    s(District, bs = "mrf", xt = list("penalty" = K)) +
    s(District, bs = "re"),
  sigma ~ 1 + rice_duration_class_long + s(sowdate_fmt_rice_day) + s(g_q5305_irrig_times_rice) + s(nperha_rice) + s(p2o5perha_rice) +
    s(c_q306_crop_larest_area_ha)+d_q401_soil_texture+d_q402_drain_class+s(m_q701_hh_member)+s(m_q708_market_distance)+irrig_source+a_q112_f_edu_new+
    population_density+wc2_1_30s_elev+sand_0_5cm+nitrogen_0_5cm+soc_5_15cm+may_tmin_17+jun_tmin_17+jul_tmin_17+aug_tmin_17+sep_tmin_17+oct_tmin_17+
    may_tmax_17+jun_tmax_17+jul_tmax_17+aug_tmax_17+sep_tmax_17+oct_tmax_17+may_prec_17+jun_prec_17+jul_prec_17+aug_prec_17+sep_prec_17+oct_prec_17+
    s(District, bs = "mrf", xt = list("penalty" = K)) +
    s(District, bs = "re")
)

set.seed(321)
library(bamlss)
b_rice_rev_MRF <- bamlss(f_rice_rev_MRF, data = Irrig_Rev_rice_wheat, family = "gaussian")

summary(b_rice_rev_MRF)


par(mfrow = c(2, 3), mar = c(4, 4, 1, 1))
plot(b_rice_rev_MRF, pages = 1, spar = FALSE, rug = TRUE)








```

# Visualization

```{r}
library(distreg.vis)
library(bamlss)

if (interactive()) {
   distreg.vis:: vis()
 }

```
